// TAG
GET http://localhost:5000/api/tags

###

POST http://localhost:5000/api/tags
Content-Type: application/json

{
    "title": "granblue-fantasy-relink",
    "url_name": "granblue-fantasy-relink"
}

###

// ARTICLE
GET http://localhost:5000/api/articles

###

POST http://localhost:5000/api/articles
Content-Type: application/json

{
      "url_name": "2273",
      "image_name": "1_mnsrl8",
      "title": "Cygames Magazine 1st Issue!",
      "category": "COMPANY",
      "tags": [],
      "content": "NULL",
      "meta_title":"Cygames Magazine 1st Issue!",
      "meta_description":"This first issue will provide a short introduction to Cygames, the background behind the establishment of this new media outlet, and a sneak peek at the kind of content we are going to be bringing you in the future."
}

###

// CATEGORY/:CATEGORY_NAME

GET http://localhost:5000/api/category/people/page/2/limit/2

###

// TAG/:TAG_NAME

GET http://localhost:5000/api/tags/cyskill/page/1/limit/2

###

// SEARCH?S=SEARCH_PARAM

GET http://localhost:5000/api/search/page/1/limit/2?s=1

###

// ARTICLES/:id

GET http://localhost:5000/api/articles/3610


###

// CLOUDINARY/images/:article

GET http://localhost:5000/api/cloudinary/images/1982