export const apiUrl =
  process.env.NODE_ENV !== "production"
    ? "http://localhost:5000/api"
    : "https://cygames-magazine-api.vercel.app/api";

export const LOCAL_STORAGE_TOKEN_NAME = "cygames-magazine";

export const ARTICLES_LOADED_SUCCESS = "ARTICLES_LOADED_SUCCESS";
export const ARTICLES_LOADED_FAIL = "ARTICLES_LOADED_FAIL";

export const TAGS_LOADED_SUCCESS = "TAGS_LOADED_SUCCESS";
export const TAGS_LOADED_FAIL = "TAGS_LOADED_FAIL";

export const ARTICLES_CATEGORY_LOADED_SUCCESS =
  "ARTICLES_CATEGORY_LOADED_SUCCESS";
export const ARTICLES_CATEGORY_LOADED_FAIL = "ARTICLES_CATEGORY_LOADED_FAIL";

export const ARTICLES_TAG_LOADED_SUCCESS = "ARTICLES_TAG_LOADED_SUCCESS";
export const ARTICLES_TAG_LOADED_FAIL = "ARTICLES_TAG_LOADED_FAIL";

export const ARTICLES_SEARCH_LOADED_SUCCESS = "ARTICLES_SEARCH_LOADED_SUCCESS";
export const ARTICLES_SEARCH_LOADED_FAIL = "ARTICLES_SEARCH_LOADED_FAIL";

export const ARTICLE_LOADED_SUCCESS = "ARTICLE_LOADED_SUCCESS";
export const ARTICLE_LOADED_FAIL = "ARTICLE_LOADED_FAIL";

export const RESET_LOADING = "RESET_LOADING";

export const ARTICLES_RANK_LOADED_SUCCESS = "ARTICLES_RANK_LOADED_SUCCESS";
export const ARTICLES_RANK_LOADED_FAIL = "ARTICLES_RANK_LOADED_FAIL";
